### ISSUE TITLE
Get the closest tslint.json file from the current file folder

### ISSUE THREAD

**Issue by jmolero** [neoclide/coc-tslint#1]
Hi. Thank you for this awesome awesome plugin. 

Would it be possible for tslint to work with the config file that's closest to the current file open? 

I get that the file could not be found when it's in a project subfolder. 
Sometimes I have project with more than one tslint.json. One in './src/server' and another in './src/client' for example.

I see that when running `CocCommand tslint.createConfig` it opens the correct file, even if it's in a subfolder.

**Comment by chemzqm** [comment]
It should find up for tslint.json up from folder of current file:
```
async function baseDir(): Promise<string> {
  let doc = await workspace.document
  let u = Uri.parse(doc.uri)
  let dir: string
  if (u.scheme !== 'file') {
    dir = workspace.cwd
  } else {
    dir = path.dirname(u.fsPath)
  }
  return dir
}

async function getConfigFile(): Promise<string> {
  let dir = await baseDir()
  return Linter.findConfigurationPath(null, dir)
}
```
if not, it's bug.

**Comment by chemzqm** [comment]
I've fixed this bug.

**Comment by jmolero** [comment]
Thanks!
