### ISSUE TITLE
Not working on typescript.tsx files 

### ISSUE THREAD

**Issue by seanmheff** [neoclide/coc-tslint#2]
Firstly, thank you for this amazing piece of software! It's a lifesaver.

I recently set up neovim for TypeScript dev. This plugin is working great on `.ts` files. They are running tslint and tsserver correctly. However, on `.tsx` files, I cannot get tslint to work at all.

I had a quick look through the code, and it seems the `client.onReady` callback in `src/index.ts` never gets called while editing `.tsx` files. Could you give me any pointers as to why that might be?

Thank you!!

**Comment by chemzqm** [comment]
This plugin doesn't use typescriptreact as filetype, which're used by coc internally.

**Comment by seanmheff** [comment]
Thank you for the quick fix!
